config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      
      put 'permissions' => 'permissions#set', as: 'set_permissions'
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root 'projects#index'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :projects do
    resources :tickets do
      member do
        post :watch
      end
    end
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  resources :users
  
  resources :files
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :permissions, as: :thing
  
  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view",
                                             user_id: user.id })
  end
  
  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end
  
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.for(current_user).page(params[:page])
    # @projects = Project.all
  end
  
  #controller actions do not need to exist in the controller
  #if there are templates corresponding to those actions
  def show
    @tickets = @project.tickets.page(params[:page])
  end 
  
  def new
    @project = Project.new  
  end
  
  def create
    @project = Project.new(project_params)
    
    if @project.save
      redirect_to @project, notice: "Project has been created."
    else
      flash[:alert] = "Project has not been created."
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project has been updated."
    else
      flash[:alert] = "Project has not been updated."
      render 'edit'
    end
  end
  
  def destroy
    @project.destroy
    
    redirect_to projects_path, notice: "Project has been deleted."
  end
  
  private
    
    def project_params
      params.require(:project).permit(:name, :description)
    end
    
    def set_project
      @project = Project.for(current_user).find(params[:id])
      
      # if current_user.admin?
      #   @project = Project.find(params[:id])
      # else
      #   @project = Project.viewable_by(current_user).find(params[:id])
      # end
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
        prohobited this project from being saved:</h2>
        
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% admins_only do %>
    <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
    <% @projects.each do |project| %>
        <li><%= link_to project.name, project %></li>
    <% end %>
</ul>
<%= paginate @projects %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'form' %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>

<% admins_only do %>
  <%= link_to "Edit project", edit_project_path(@project) %>
  <%= link_to "Delete project", 
              @project,
              method: :delete,
              data: { confirm: "Are you sure you want to delete project #{@project.name}?" 
                    } %>
<% end %>
<h2>Tickets</h2>
<% authorized?("create tickets", @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<ul id='tickets'>
  <% @tickets.each do |ticket| %>
    <li>
      <%= ticket.state if ticket.state %> #<%= ticket.id %> - <%=  link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

<%= paginate @tickets %>