config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      
      put 'permissions' => 'permissions#set', as: 'set_permissions'
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root 'projects#index'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :projects do
    resources :tickets do
      member do
        post :watch
      end
    end
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  resources :users
  
  resources :files
  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def remove
    @ticket = Ticket.find(params[:ticket_id])
    if current_user.admin? || can?("tag".to_sym, @ticket.project)
      @tag = Tag.find(params[:id])
      @ticket.tags -= [@tag]
      @ticket.save
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<p>
  <%= f.label :tag_names, "Tags" %>
  <%= f.text_field :tag_names %>
</p>

app/views/tags/_tag.html.erb
<span class='tag'>
  <% if current_user.admin? || can?("tag".to_sym, @ticket.project) %>
    <%= link_to "x", remove_ticket_tag_path(@ticket, tag),
                     method: :delete,
                     remote: true,
                     id: "delete-#{tag.name.parameterize}" %>
  <% end %>
  <%= tag.name %>
</span>

app/views/tags/remove.js.erb
$('#delete-<%= @tag.name.parameterize %>').parent().remove()