config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      
      put 'permissions' => 'permissions#set', as: 'set_permissions'
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root 'projects#index'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :projects do
    resources :tickets do
      member do
        post :watch
      end
    end
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  resources :users
  
  resources :files
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :permissions
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.order(:email).page(params[:page])
  end
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    params = user_params.dup
    params[:password_confirmation] = params[:password]
    params[:name] = params[:email]
    @user = User.new(params)
    
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been created."
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render 'edit'
    end
  end
  
  def destroy
    if @user == current_user
      flash[:alert] = "You can not delete yourself!"
    else
      @user.destroy
      
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end
  
  private
    def user_params
      params.require(:user).permit(:name, 
                                   :email, 
                                   :password, 
                                   :password_confirmation, 
                                   :admin)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def show
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have signed up successfully."
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = "Profile has been updated."
      redirect_to @user
    else
      flash[:alert] = "Profile has not been updated."
      render 'edit'
    end
  end
  
  private 
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def set_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The user you were looking for could not be found."
      redirect_to projects_path
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohobited this user from being saved:</h2>
        
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing a user</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h2>Users</h2>
<%= link_to 'New User', new_admin_user_path %>
<ul id="users">
  <% @users.each do |user| %>
    <li><%= user.name %> | <%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", 
            admin_user_path(@user), 
            method: :delete, 
            data: { confirm: "Are you sure you want to delete #{@user}?" } %>
<%= link_to "Permissions", admin_user_permissions_path(@user) %>