config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      
      put 'permissions' => 'permissions#set', as: 'set_permissions'
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  root 'projects#index'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :projects do
    resources :tickets do
      member do
        post :watch
      end
    end
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  resources :users
  
  resources :files
  

end

app/models/state.rb
class State < ActiveRecord::Base
  
  def to_s
    name
  end
  
  def default!
    current_default_state = State.find_by(default: true)
    
    self.default = true
    self.save
    
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  
  def index
    @states = State.all
  end
  
  def new
    @state = State.new
  end
  
  def create
    @state = State.new(state_params)
    
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render 'new'
    end
  end
  
  def make_default
    @state = State.find(params[:id])
    @state.default!
    
    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end
  
  private
  
    def state_params
      params.require(:state).permit(:name, :background, :color)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for([:admin, @state]) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %>
        prohobited this state from being saved:</h2>
        
        <ul>
          <% @state.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>
<ul id='states'>
  <% @states.each do |state| %>
  <li id='state_<%=state.id %>'>
    <%= state.name %>
    <%= link_to "Make Default", make_default_admin_state_path(state) %>
  </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render 'form' %>